### ISSUE TITLE
Allow `@React`ing and `@Command`ing on entity state updates

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#1204]
Currently, it is only possible to `@Subscribe` on entity state updates, but technically we can allow users to `@React` and `@Command` to state updates as well.

That's smth we'd probably need to discuss more, cause it may allow developers to abuse such power and lead to bad design decisions.

The issue is somehow also related to #1203, cause it's not possible now to filter with `@Where` the entity states.

**Comment by alexander-yevsyukov** [comment]
You're essentially suggest a database trigger implemented in the Java code :) I think it would make the code less event-centric. We gave the ability to subscribe to entity states so that we can accumulate data in projections. But the rest of the code should listen to events. It would be easier to learn and analyse.
