### ISSUE TITLE
Rename `Nothing` type to avoid confusion with Kotlin's

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#1335]
Kotlin has standard type which is named `Nothing`. It is used in function declarations when it never returns because of throwing an exception.

We have a specialized `Message` type, `io.spine.server.model.Nothing`, which serves as a return type of handler methods that do not return anything. These methods do return an instance of such message and exit normally. 

This may bring various confusions for Kotlin people:
 * **Why do we have a handler method that never completes?** Just by looking at the method signature, it's not possible to tell that it's Spine-specific  `Nothing`, not the standard Kotlin's one.
 * **What doesn't this handler work?** I don't know what declaring wrong `Nothing` in a Kotlin code for a handler would cause, but I'm not sure it would be OK.
 * Fully-qualified Spine's `Nothing` when the user's code needs to use Kotlin's one.
 * etc.

In order to avoid this confusion we need to have a type with another name.

**Comment by alexander-yevsyukov** [comment]
To be mentioned as breaking change in [Release Notes](https://github.com/SpineEventEngine/SpineEventEngine.github.io/issues/409).

**Comment by alexander-yevsyukov** [comment]
Suggested alternative name: `None`.

**Comment by alexander-yevsyukov** [comment]
Previously suggested empty `Tuple` type won't work because our `Nothing` is frequently used in tules like this: `EitherOf2<JobComplete, Nothing>`.

**Comment by armiol** [comment]
@alexander-yevsyukov 
We can only return `Nothing` in reaction to some event, which we may or may not want to react upon.
It is impossible to return `Nothing` from a command handler for obvious reasons.

`NoReaction` reflects what we want to say perfectly: 

  _"Something has happened, and we could potentially react on it. But at this time, we chose not to."_

Using `NothingHappened` is misleading, because it sounds like an event. But as stated earlier, some event _has_ happened—we just don't want to react.

Therefore, I'd stick to `NoReaction` as a `typealias`. And I would drop `NothingHappened`.

**Comment by alexander-yevsyukov** [comment]
> Therefore, I'd stick to `NoReaction` as a `typealias`. And I would drop `NothingHappened`.

Yeah, see this [commit](https://github.com/SpineEventEngine/core-java/pull/1549/commits/039768068c649b065b4ffd0668c098ad7503d5a9).
