### ISSUE TITLE
[1.x] Empty aggregate `state()` just after snapshot 

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/core-java#1499]
In the `@Apply` method handler just after the snapshot `state()` object is a `DefaultInstance`.  

Steps to reproduce: 
1. Aggregate, one `@Assign` and one `@Apply` method;
2. Update state via `builder()` in the `@Apply` method;
3. Emit 100 commands to this aggregate;
4. Emit one more command to the aggregate;
5. The `@Apply` method is called to build the state;
6. Check `state()`, it will be `DefaultInstance`.

**Comment by armiol** [comment]
@dmytro-kashcheiev I have analysed this use-case, and it turns out the `state()` behaves as designed in this case. It is impossible to expect something other than a default state until the transaction is committed. While technically it is possible for the framework-internal code to populate both `state()` and `builder()` when restoring from a snapshot, such an approach breaks a nature of the ongoing transaction (e.g., making it impossible to perform a rollback).

Therefore, we just prohibit calling `state()` from within an applier method. See #1501.

**Comment by armiol** [comment]
Closing as resolved via #1501.
