### ISSUE TITLE
Allow to subscribe to all Failures of a certain type regardless of the origin Command.

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#462]
At the moment the subscription to a certain `Failure` requires to specify the original `Command`:

```java
@Subscribe
public void onCannotCreateProject(Failures.CannotCreateProject failure, 
                                  CreateProject commandMessage,
                                  CommandContext context) {
    // Handles the failure thrown while processing command `CreateProject`
}
```
The `context` parameter in the declaration is optional.

It should be possible to subscribe to all Failures of the type like this:
```java
@Subscribe
public void onCannotCreateProject(Failures.CannotCreateProject failure,
                                  CommandContext context) {
    // Handles the failure whenever it's thrown
}
```
or like this
```java
@Subscribe
public void onCannotCreateProject(Failures.CannotCreateProject failure) {
    // Handles the failure whenever it's thrown
}
```

**Comment by dmdashenkov** [comment]
In order to implement this feature, it is decided to make the next declaration an invalid Failure handler
```java
@Subscribe
public void onCannotCreateProject(Failures.CannotCreateProject failure,
                                  CreateProject commandMessage) {
    // Handles the failure thrown while processing command `CreateProject`
}
```

As the result, there are 3 possible param sets for a Failure handler method:
 - `(Message failureMessage)` - single parameter;
 - `(Message failureMessage, CommandContext context)` - two parameters;
 - `(Message failureMessage, Message commandMessage, CommandContext context)` - three parameters.

As stated above, the count of parameters unambiguously shows what case do we have and if we should filter the Failures by the produced by the type of the Command or not.
